# Generated by Django 2.2.5 on 2020-11-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201105_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rulse',
            new_name='house_rules',
        ),
    ]
